deno.json
=> feat: `deno task check`

deno.json
This is an easy way to check that everything's alright locally and in CI (to come).
=> feat: `deno task ok`

demo.ts, deps.ts, mod.ts, test.ts
This makes managing dependencies easier.
=> refactor: centralize dependencies

demo.ts, deps.ts, mod.ts, test.ts
=> feat: conditionally secure cookies

demo.ts
This small change improves the ergonomics of the demo app for future provider support.
=> refactor: demo to improve provider onboarding

README.md, demo.ts, mod.ts, test.ts
Closes #16. 
Also, added optional scopes argument to sign in (otherwise discord would be unusable as a client).
=> feat: discord client

src/create_client.ts
=> feat: google client

README.md
=> docs: fix link to demo site in README

README.md, demo.ts, src/create_client.ts, src/create_client_test.ts, src/sign_out_test.ts
=> feat: Twitter client

src/create_oauth2_client.ts
Addresses https://github.com/denoland/deno_kv_oauth/pull/79#discussion_r1225988072
=> fix: require `additionalOAuth2ClientConfig` where `redirectUri` and/or `scope` are required

deno.json
Tests are already plenty fast. But this makes them faster.
Before: 1s
After: 263ms
Inspired by https://github.com/denoland/fresh/pull/1281
=> chore: parallel tests

.github/workflows/ci.yml
=> chore(ci): test on canary

README.md, src/create_oauth2_client.ts, src/create_oauth2_client_test.ts
=> feat: createFacebookOAuth2Client

README.md, src/create_oauth2_client.ts, src/create_oauth2_client_test.ts
Extra client for the list. See [Dropbox OAuth docs](https://developers.dropbox.com/oauth-guide)
=> feat: `createDropboxOAuth2Client()`

deno.json
=> chore: correct update task

README.md
This also includes a minor README restructure that follows the flow of the new getting started section.
=> docs: improved "Getting Started" section

README.md
This _may_ prevent PRs like #111 from being created.
=> fix: reduce `deno.lock` changes

src/core_test.ts
Done using [typos](https://github.com/crate-ci/typos).
=> fix: typos

README.md
=> feat: add reference to Ultra demo

README.md, demo.ts, src/providers.ts, src/providers/auth0.ts, src/providers_test.ts
I based it on the Okta provider, I believe they're pretty similar. Let me know if I missed anything!
=> feat: `createAuth0OAuth2Client()`

dev_deps.ts
See https://github.com/denoland/deno_std/pull/3445
=> chore: migrate remaining assertions

README.md
Just adding a production app that uses deno_kv_oauth in the showcase.
=> docs: add Paquet to showcase

README.md
Related #152 and #79
CC @lino-levan and @mitchwadair
=> docs: add "Twitch Incompatibility" README section

README.md
=> docs: show how to use access token

README.md, src/core.ts, src/sign_in.ts, src/sign_out.ts
=> docs: add "Redirect URL after Sign-In or Sign-Out" section to README

src/core.ts
=> fix: remove key expiry from `setTokens()`

demo_test.ts, src/clear_oauth_sessions_and_tokens_test.ts, src/core_test.ts, src/get_session_access_token_test.ts, src/handle_callback_test.ts, src/sign_out_test.ts, src/test_utils.ts
To keep things a little DRYer.
=> chore: add object generator test utilities

.github/workflows/update.yml
=> fix: lcov generation for `Update dependencies` workflow

src/core_test.ts, src/get_session_access_token_test.ts, src/get_session_id_test.ts, src/handle_callback_test.ts, src/sign_in_test.ts, src/sign_out_test.ts, src/test_utils.ts
This is mainly done for readability.
=> chore: flatten tests

dev_deps.ts, lib/get_session_access_token.ts, lib/get_session_access_token_test.ts, lib/handle_callback.ts, lib/handle_callback_test.ts
Feel free to review, @mitchwadair, since you're good at picking up my mistakes 😆
Note: test coverage will drop once the Fresh plugin is temporarily re-added to the module in #219.
=> chore: 100% test coverage

lib/fresh_plugin_test.ts
These tests are deliberately basic, and the handlers return the test that redirect responses. The internal logic of these handlers is tested elsewhere in the module.
=> chore: improve Fresh plugin test coverage

lib/_http.ts, lib/_http_test.ts, lib/_kv.ts, lib/_kv_test.ts, lib/_test_utils.ts, lib/fresh_plugin_test.ts, lib/get_session_id.ts, lib/get_session_id_test.ts, lib/handle_callback.ts, lib/handle_callback_test.ts, lib/sign_in.ts, lib/sign_in_test.ts, lib/sign_out.ts, lib/sign_out_test.ts
This makes internal utilities easier to spot.
=> refactor: separate internal KV and HTTP utilities

README.md
This PR aims to improve the understandability of this module and how to use it. Any change that doesn't achieve this should be redone.
=> docs: re-write README

lib/_http.ts, lib/_kv.ts, lib/get_required_env.ts, lib/get_session_id.ts, lib/handle_callback.ts, lib/sign_in.ts, lib/sign_out.ts
Now, only comments are only provided when they add context that would otherwise be missing.
=> chore: cleanup comments

README.md, deno.json, lib/create_auth0_oauth_config.ts, lib/create_discord_oauth_config.ts, lib/create_dropbox_oauth_config.ts, lib/create_facebook_oauth_config.ts, lib/create_github_oauth_config.ts, lib/create_gitlab_oauth_config.ts, lib/create_google_oauth_config.ts, lib/create_notion_oauth_config.ts, lib/create_okta_oauth_config.ts, lib/create_patreon_oauth_config.ts, lib/create_slack_oauth_config.ts, lib/create_spotify_oauth_config.ts, lib/create_twitter_oauth_config.ts, lib/get_required_env.ts, lib/get_session_id.ts, lib/handle_callback.ts, lib/sign_in.ts, lib/sign_out.ts
There appears to be no need for this.
=> docs: remove `@$VERSION` from imports

lib/_kv.ts
This ensures that the OAuth session entry hasn't changed between the get and delete operations.
=> fix: check OAuth session before deletion

lib/create_github_oauth_config.ts, lib/create_notion_oauth_config.ts
I fixed two typos. Please check it.
=> chore: fix typos

README.md
=> docs: link to Fastro demo

demo.ts, deps.ts, lib/_http.ts, lib/_test_utils.ts
=> refactor: replace `Status` with `STATUS_CODE`

README.md, deno.json
See https://deno.com/blog/v1.40#changes-to-how-we-handle-unstable-features
=> chore: use granular `--unstable-*` flags

README.md, deno.json, lib/create_auth0_oauth_config.ts, lib/create_azure_ad_oauth_config.ts, lib/create_azure_adb2c_oauth_config.ts, lib/create_discord_oauth_config.ts, lib/create_dropbox_oauth_config.ts, lib/create_facebook_oauth_config.ts, lib/create_github_oauth_config.ts, lib/create_gitlab_oauth_config.ts, lib/create_google_oauth_config.ts, lib/create_helpers.ts, lib/create_notion_oauth_config.ts, lib/create_okta_oauth_config.ts, lib/create_patreon_oauth_config.ts, lib/create_slack_oauth_config.ts, lib/create_spotify_oauth_config.ts, lib/create_twitter_oauth_config.ts, lib/get_required_env.ts, lib/get_session_id.ts, lib/handle_callback.ts, lib/sign_in.ts, lib/sign_out.ts
This will make make JSR migration work a little cleaner.
=> docs: remove version from import specifiers
