denoland/deno_kv_oauth

- demo.ts
- mod.ts
- test.ts
This change:
1. Adds `getSessionTokens()`
2. Removes `getUser()`
3. Simplifies other parts of the API as a result.
Closes #33.
> feat: `getSessionTokens()`

- src/sign_out.ts
- src/sign_out_test.ts
You need to set the path to the top level path (cookies are really hard, trust me, I know), otherwise sign out will not work for nested paths (i.e. `/api/logout`). 
Here's a test you can do to see the difference of behavior. The `/api/logout` doesn't work at all here. Replace the `deno_kv_oauth` import with this branch to see the fix.
```ts
// deno run --unstable --allow-env --allow-net demo.ts
import {
createClient,
getSessionTokens,
handleCallback,
isSignedIn,
signIn,
signOut,
} from "https://deno.land/x/deno_kv_oauth/mod.ts";
import { serve, Status } from "https://deno.land/std/http/mod.ts";
import "https://deno.land/std/dotenv/load.ts";
const client = createClient("github");
async function indexHandler(request: Request) {
let body = `
<p>Who are you?</p>
<p><a href="/api/login">Sign …
```
> fix: sign out

- README.md
- demo.ts
- mod.ts
- src/get_session_id.ts
- src/get_session_id_test.ts
- src/get_session_tokens.ts
- src/get_session_tokens_test.ts
- src/handle_callback.ts
- src/sign_out.ts
- src/sign_out_test.ts
This change:
- Adds `getSessionId(request: Request): string | null`, which is more versatile than `isSignedIn()`. This will also help projects that currently implement OAuth transition.
- Removes `isSignedIn()`, as `getSessionId()` can be used in the same capacity by checking if truthy.
- Replaces instances of `siteSessionId` with just `sessionId`.
- Simplifies `getSessionTokens()` to accept `sessionId: string`.
> feat: add `getSessionId()`

- demo.ts
- src/handle_callback.ts
Usually, some setup is performed within the callback handler. This helps with that.
> refactor: `handleCallback()` returns `response`, `tokens` and `sessionId`

- deps.ts
- src/handle_callback.ts
- src/handle_callback_test.ts
Unfortunately, 100% coverage is not possible.
> chore: add `handleCallback()` tests

- README.md
- src/create_client.ts
- src/create_client_test.ts
~~This is a "classic" slack app instead of a "new" slack app, but "new" slack apps aren't really oauth so probably out-of-scope for this module.~~
We decided to go with the "new" slack oauth option for now. Please make some noise if you need the old one for some reason.
> feat: slack client

- demo.ts
- src/get_session_id.ts
- src/get_session_id_test.ts
- src/sign_out.ts
This change adds a KV check into `getSessionId()` that ensures a token exists for a given `sessionId`.
> feat: `getSessionId()` checks KV

- deps.ts
- dev_deps.ts
- src/_core.ts
- src/_core_test.ts
- src/create_client.ts
- src/create_client_test.ts
- src/get_session_access_token_test.ts
- src/get_session_id_test.ts
- src/handle_callback.ts
- src/handle_callback_test.ts
- src/sign_in_test.ts
- src/sign_out_test.ts
- tools/check_license.ts
This PR splits external dependencies to 2 files, `deps.ts` and `dev_deps.ts`. Now the runtime code only depends on `deps.ts`. This prevents unnecesary modules (ex. `std/testing`, `std/path`, `std/fs`) exported to the users' module.
> perf: split runtime and dev dependencies

- demo.ts
This fix slightly simplifies the signed-in/signed-out logic of the demo and corrects the signout link, which previously wasn't working.
> fix: demo sign out

- README.md
- deno.json
- src/_core.ts
- src/get_session_access_token_test.ts
- src/get_session_id_test.ts
- src/sign_in_test.ts
- src/sign_out_test.ts
This change allows the user to define a `KV_PATH` environment variable to choose the KV's path. It works such that if `--allow-env` permissions aren't set, the code doesn't complain. By setting `KV_PATH=:memory:`, test cleanups are no longer needed.
Closes #88
Likely closes #87
> feat: `KV_PATH` environment variable

- src/_core.ts
- src/get_session_id.ts
Getting the token with strong consistency is now the fail-through.
> perf: try eventual consistency first in `getSessionId()`

- deno.json
- src/create_oauth2_client.ts
- src/get_session_access_token.ts
- src/get_session_id.ts
- src/handle_callback.ts
- src/sign_in.ts
- src/sign_out.ts
Previously, when checking docs, an error would be thrown because of a mismatch in functionality between the latest stable version of the module and the canary version of the module. This change fixes that.
> doc: tweak imports in docs

- src/create_oauth2_client_test.ts
This'll make adding provider clients easier.
> refactor: DRY `createOAuth2Client()` tests

- demo.ts
The previously printed error was misleading, as the error behaviour was expected.
> fix: remove print error

- README.md
- demo.ts
This also adds `scope` to the demo.
> docs: add "Running the Demo" and "Adding a Pre-configured OAuth 2.0 Client" README sections

- src/core.ts
- src/core_test.ts
- src/get_session_access_token_test.ts
This slight change ensures that `isSecure()` only accepts valid URLs. More testing for `getSessionAccessToken()` and `getCookieName()` are also included.
> refactor: `isSecure()`

- .github/workflows/ci.yml
Done using the [typos GitHub action](https://github.com/crate-ci/typos/blob/master/docs/github-action.md).
Idea was taken from https://github.com/denoland/deno_std/pull/3459.
> chore: check typos in CI

- .vscode/settings.json
- README.md
- demo.ts
- src/get_session_id.ts
- src/get_session_id_test.ts
- src/sign_out.ts
This allows for `fn(sessionId?: string)` instead of `fn(sessionId: string | null)` and seems more intuitive, IMO.
> BREAKING: return `undefined` instead of `null` from `getSessionId()`

- demo.ts
- dev_deps.ts
Deno Deploy now supports `Deno.serve()`.
> refactor: use `Deno.serve()` in demo

- src/sign_in.ts
- src/sign_in_test.ts
This was mainly to resolve an issue with Auth0 tokens but may useful for other oauth2 providers.
For Auth0 specifically, if an `audience` search parameter isn't provided then the resulting token is an opaque one, with no body.
This means that the token cannot be used in conjunction with the [Auth0 APIs.](https://auth0.com/docs/api) This fix should hopefully fix that for Auth0 tokens (and by extension other providers should they also need additional url parameters to be added).
Example of the access token that is sent back to the end user with the possible patch
> feat: option to append URL params to authorization URI for `signIn()`

- README.md
- demo.ts
- src/get_session_access_token.ts
- src/get_session_id.ts
- src/get_session_id_test.ts
- src/sign_out.ts
Previously, `getSessionId()` did two things before returning the session ID:
1. Retrieved the cookie value (session ID) from the request object.
2. Checked whether that session object exists in KV.
This change removes step two. `getSessionId()` is often used with `getSessionAccessToken()`, and `getSessionAccessToken()` also retrieves said session object. So, when used together, two getters for the session object in KV are made.
Now, `getSessionId()` just gets the session ID from the cookie value in the request.
Thanks to @adoublef for pointing this out!
Concerns:
1. Is `getSessionId()` still a valid and reasonable method of checking whether the client is signed in? I think so.
2. Could `getSessionId()` be renamed to communicate more clearly that this function is only concerned with …
> BREAKING: remove KV call from `getSessionId()`

- README.md
- mod.ts
- src/clear_oauth_sessions_and_tokens.ts
- src/clear_oauth_sessions_and_tokens_test.ts
- src/core.ts
Even once key expiration comes to Deno KV, there will be instances where KV entries will need to be deleted. E.g. migrations.
Supersedes #151
> feat: `clearOAuthSessionsAndTokens()`

- deno.json
This will provide further context for when tests fail. Thought I'd add this due to https://github.com/denoland/deno_kv_oauth/actions/runs/5970246683/job/16197528484
> chore: add `--trace-ops` to `test` task

- demo_test.ts
- src/clear_oauth_sessions_and_tokens.ts
- src/clear_oauth_sessions_and_tokens_test.ts
- src/core.ts
- src/core_test.ts
- src/get_session_access_token.ts
- src/get_session_access_token_test.ts
- src/handle_callback.ts
- src/sign_out.ts
- src/sign_out_test.ts
This change replaces the `stored_tokens_by_session` index with the `tokens` index. The legacy index with be deleteable until v1 of this module is released.
> refactor: drop `stored_tokens_by_session` index

- src/core.ts
- src/core_test.ts
This PR fixes a small bug where the `expiresIn` value calculated by `toTokens` was incorrect. This was happening because the operands were reversed. When calculating the value for `expiresIn`, we want to subtract the current time from the time the token will expire at. With the previous logic, the expiry time was being subtracted from the current time, causing `expiresIn` to be a negative number when it should have been positive.
Covers part of #199 
I updated the test to also make sure `expiresIn` is greater than 0 as a regression test (do we want to tighten the value comparison logic at all?). Tests are passing locally
> fix: correct `expiresIn` calculation in `toTokens()`

- deno.json
To accompany the `cov:gen` and `cov:view` tasks when working locally.
> chore: add `cov:clean` task

- README.md
- deno.json
- lib/fresh_plugin.ts
- lib/fresh_plugin_test.ts
- mod.ts
This change adds the Fresh plugin back to this module. Frankly, #192 was merged prematurely (my bad). This allows us to cut a release with some important updates without waiting for Fresh's next release. This plugin will be removed upon Fresh's new release, which will be the new home for the Deno KV OAuth Fresh plugin. A few small notable changes:
1. No `/fresh.ts` - just import from `/lib/fresh_plugin.ts`
2. It's been updated to use `OAuth2ClientConfig` instead of `OAuth2Client`, like the rest of the codebase
> revert: Fresh plugin removal (#192)

- README.md
- lib/handle_callback.ts
- lib/sign_in.ts
- lib/types.ts
- mod.ts
This change removes the need to import `OAuth2ClientConfig` from the x/oauth2_client module.
> feat: export `OAuth2ClientConfig` interface

- lib/_http.ts
- lib/_http_test.ts
- lib/get_session_id.ts
- lib/handle_callback.ts
- lib/sign_in.ts
- lib/sign_out.ts
This name is clearer. This also simplifies the logic. It's safe to assume the input is indeed a URL string.
> refactor: rename `isSecure()` to `isHttps()`

- lib/sign_out.ts
- lib/sign_out_test.ts
Previously, this check was justified because it could potentially avoid a database call. Now that the database call is gone, the check can be removed.
> refactor: remove unnecessary cookie check from `signOut()`

- README.md
The functions are "GitHub" otherwise the code in the README doesn't work.
> fix: GitHub exports in README for Fresh demo

- lib/sign_out.ts
This change makes all chosen `cookieOptions` properties optional.
> fix: make `cookieOptions` partial for `signOut()`

- lib/sign_out.ts
The ability to define the cookie name using `options?.cookieOptions?.name` was already there. However, this makes it clear that that is the case.
> fix: clarify ability to define cookie name

- README.md
- lib/get_session_id.ts
- lib/handle_callback.ts
- lib/sign_out.ts
This piece was missed when adding cookie options to `handleCallback()` and `signOut()`.
> feat: cookie name option for `getSessionId()`

- README.md
- lib/create_helpers.ts
- mod.ts
This reduces the amount of configuration repetition when using this module. As seen in the README changes, this is particularly helpful when setting one's custom cookie settings.
This idea is made to compete with the `Client` class idea in #253. I prefer this change, as a factory function is more straightforward to conceptualise and maintain over a class, IMO.
> feat: add `createHelpers()`

- deps.ts
- lib/_http.ts
- lib/_kv.ts
- lib/create_helpers.ts
- lib/get_required_env.ts
- lib/get_session_id.ts
- lib/handle_callback.ts
- lib/sign_out.ts
This immediately makes return types visible and prevents some breaking changes to return types.
> refactor: add function return types

- lib/_kv.ts
Every use case uses the expiry field anyway.
> fix: make `OAuthSession` expiry compulsory

- .github/workflows/ci.yml
- .github/workflows/update.yml
When new platform versions are published, this will be one less thing to consider.
> chore: use `*-latest` platforms

- README.md
- demo.ts
- lib/_http.ts
- lib/_kv.ts
- lib/create_helpers.ts
- lib/get_session_id.ts
- lib/get_session_id_test.ts
- lib/handle_callback.ts
- lib/sign_out.ts
- lib/sign_out_test.ts
This change adds a database check to `getSessionId()` and `signOut()`.
A session ID entry is created in KV on the originating server. This entry is then checked for and deleted when appropriate.
> fix: add site session database check

- README.md
- deno.json
- tools/check_license.ts
I was working on re-introducing the Fresh plugin and realised it might be best to have a "Get Started with Fresh" section instead. A clear, easy-to-follow guide instead of a plugin would avoid the engineering cost that a Fresh plugin would incur. `createHandlers()` also provides most of the consistency benefits a Fresh plugin would have.
This section provides a solid starting point for those wanting to use Fresh and this module.
> docs: rework "Get Started with Fresh" section

- README.md
- deno.json
- lib/create_auth0_oauth_config.ts
- lib/create_discord_oauth_config.ts
- lib/create_dropbox_oauth_config.ts
- lib/create_facebook_oauth_config.ts
- lib/create_github_oauth_config.ts
- lib/create_gitlab_oauth_config.ts
- lib/create_google_oauth_config.ts
- lib/create_helpers.ts
- lib/create_notion_oauth_config.ts
- lib/create_okta_oauth_config.ts
- lib/create_patreon_oauth_config.ts
- lib/create_slack_oauth_config.ts
- lib/create_spotify_oauth_config.ts
- lib/create_twitter_oauth_config.ts
- lib/get_required_env.ts
- lib/get_session_id.ts
- lib/handle_callback.ts
- lib/sign_in.ts
- lib/sign_out.ts
Leaving this string in encourages version pinning, which is a good practice.
> revert: remove `@$VERSION` from imports

- .github/workflows/update.yml
The `peter-evans/create-pull-request@v6` action requires the `token` field to be defined for the `codecov/codecov-action@v4` action.
See https://github.com/codecov/codecov-action#usage
> chore: fix `update` workflow

- README.md
- lib/create_aws_cognito_oauth_config.ts
- lib/create_cognito_user_pool_oauth_config.ts
- mod.ts
Adds the configuration for a Cognito User Pool provider.
This assumes users have their user pool app client properly configured. Namely, it needs to have a client secret generated, have the appropriate callback URLs registered, and support the AuthorizationCodeGrant flow. 
Resolves #310
> feat: `createAwsCognitoOAuthConfig()`

- README.md
- lib/create_helpers.ts
- lib/create_helpers_test.ts
- lib/get_session_id.ts
- lib/handle_callback.ts
- lib/sign_in.ts
- lib/sign_out.ts
This change deprecates `signIn()`, `handleCallback()`, `signOut()`, and `getSessionId()` in favour of the functions created from `createHelpers()`. This ensures that the behaviour of helpers is consistent throughout various pages. The `Helper` interface will make the documentation of these functions easier to read.
Supercedes #312
> feat: `Helpers` interface
